### ISSUE TITLE
Make matching case insensitive

### ISSUE THREAD

**Issue by remal** [ZeWaka/KeywordLabeler#15]
If I understand correctly, the bot matches titles and bodies in a case sensitive manner. It means that `[WIP]` doesn't match `[wip]`. Could you please make the matching process case insensitive (by applying `toLoserCase()` to titles, bodies and tokens)?

**Comment by ZeWaka** [comment]
This sounds good as an optional configuration, something like `caseSensitive: false`, with it defaulting to `true`

**Comment by remal** [comment]
It works awesome, thank you!
