### ISSUE TITLE
Application not working

### ISSUE THREAD

**Issue by Ausyys** [ZeWaka/KeywordLabeler#20]
[URGENT] Hi, I've installed your app, and I've gone through the guide and I've done it but it's not working.
Please help, I'm a beginner in Github.

here:
![Screenshot (352)](https://user-images.githubusercontent.com/70477317/94144057-93ec1d00-fe68-11ea-8e36-adb5479e9c49.png)
and:
![Screenshot (353)](https://user-images.githubusercontent.com/70477317/94144060-95b5e080-fe68-11ea-8960-f1fb9d07a801.png)
thanks🙏

**Comment by ZeWaka** [comment]
Hi, did you create the labels on your repository? I can't see since I'm not a contributor, but in order for the labeler to apply the labels they have to exist.

**Comment by ZeWaka** [comment]
Oh, I see. You seem to have created a new repository named .github and put the file there. You need to put the labeler in a FOLDER named `.github` in the repository you have the GitHub app installed to (where your program would be).
