### ISSUE TITLE
Doesn't appear to be working after following instructions.

### ISSUE THREAD

**Issue by camdan-me** [ZeWaka/KeywordLabeler#21]
Config file located in `.github/keylabeler.yml`:
```yaml
matchTitle: true
matchBody: false
caseSensitive: false

labelMappings:
  "[BREAKING]": "BREAKING CHANGE"
  P0:P0
  P1:P1
  P2:P2
  P3:P3
```
Labels: ![labels](https://cam.is-ne.at/GTyZYY.png)

As far as I know the app has the access it needs.

**Comment by ZeWaka** [comment]
Well, those `PX` labels aren't setup properly in the .yml format, so that's likely breaking the whole file.

YAML specifies a space be after the colon, test with something like this: http://www.yamllint.com/

**Comment by camdan-me** [comment]
Nice catch, thanks!
