### ISSUE TITLE
Misbehaviour on modifying of a PR of a contributor

### ISSUE THREAD

**Issue by Suvraneel** [ZeWaka/KeywordLabeler#22]
**Describe the bug**
Adding labels even though there is none of the targeted keywords

**To Reproduce**
Changing heading made by a contributor

OR 

Changing branch of merge by a maintainer

**Expected behavior**
Nothing

**Screenshots**
![image](https://user-images.githubusercontent.com/63473496/134116106-1319a4c7-9033-4d43-85ff-49ef407a00df.png)

**Comment by ZeWaka** [comment]
I cannot reproduce with those steps. Your configuration is likely wrong.
