### ISSUE TITLE
Support regular expressions

### ISSUE THREAD

**Issue by leandro-lucarella-frequenz** [ZeWaka/KeywordLabeler#23]
**Is your feature request related to a problem? Please describe.**

It is difficult to avoid *false positives* unless the keyword is very rare.

**Describe the solution you'd like**

I would like to be able to use regexp to be a bit more specific about when to tag. For example, I want to label titles starting with `ci: ` with a `ci` label. But if I use `ci: ` then something like `@pepe-paci: please look at this` will match. In this case I would use `^ci: ` as keyword or match expression.

**Describe alternatives you've considered**

The only alternative I see is just to use rarer keywords, like `[ci] `, but then I need to change already existing conventions for my repos, which is rather inconvenient.

**Comment by VincentLanglet** [comment]
Hi @ZeWaka What do you think about this feature ?

I would say it require to change
https://github.com/ZeWaka/KeywordLabeler/blob/master/app.js#L12-L16
to 
```
const config = await context.config("keylabeler.yml", {
        matchTitle: true,
        matchBody: true,
        caseSensitive: true,
        useRegex: false,
      });
```

and https://github.com/ZeWaka/KeywordLabeler/blob/master/app.js#L44-L45
to use `.match` instead of `.includes` if `useRegex` is true.

I can do the dev if you want

**Comment by ZeWaka** [comment]
> Hi @ZeWaka What do you think about this feature ?
> I can do the dev if you want

Sure, feel free to submit a PR!

**Comment by VincentLanglet** [comment]
> > Hi @ZeWaka What do you think about this feature ?
> > I can do the dev if you want
> 
> Sure, feel free to submit a PR!

Sure https://github.com/ZeWaka/KeywordLabeler/pull/25
